apiVersion: v1
kind: Service
metadata:
  name: lms-gateway
  namespace: itgura
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: lms-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
