services:
  postgres-main:
    container_name: postgres-main
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: itgura
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-main
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres-main
    restart: unless-stopped

  eureka-server:
    container_name: eureka-server
    image: yesitha/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  lms-gateway:
    container_name: lms-gateway
    image: yesitha/lms-gateway:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=lms-gateway
    depends_on:
      - eureka-server
    networks:
      - spring

  auth-service:
    container_name: auth-service
    image: yesitha/auth-service:latest
    ports:
      - "8098:8098"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=auth-service
    depends_on:
      - eureka-server
      - postgres-main
    networks:
      - spring
      - postgres-main

  payment-service:
    container_name: payment-service
    image: yesitha/payment-service:latest
    ports:
      - "8199:8199"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=payment-service
    depends_on:
      - eureka-server
      - postgres-main
    networks:
      - spring
      - postgres-main

  resource-management:
    container_name: resource-management
    image: yesitha/resource-management-all:latest
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=resource-management
    depends_on:
      - eureka-server
      - postgres-main
    networks:
      - spring
      - postgres-main

  dms-mediator:
    container_name: dms-mediator
    image: yesitha/dms-mediator-all:latest
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=dms-mediator
      - ALFRESCO_BASE_URL=http://alfresco:8080
    depends_on:
      - eureka-server
      - alfresco
    networks:
      - spring

#  alfresco:
#    container_name: alfresco
#    image: alfresco/alfresco-content-repository-community:latest
#    environment:
#      JAVA_OPTS: "
#        -Ddb.driver=org.postgresql.Driver
#        -Ddb.username=postgres
#        -Ddb.password=root
#        -Ddb.url=jdbc:postgresql://postgres-main/alfresco
#        -Dsolr.host=solr6
#        -Dsolr.port=8983
#        -Dsolr.secureComms=none
#        -Dsolr.base.url=/solr
#        -Dindex.subsystem.name=solr6
#        -Dalfresco.host=localhost
#        -Dalfresco.port=8080
#        -Dalfresco.context=alfresco
#        -Dalfresco.protocol=http"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres-main
#      - solr6
#    networks:
#      - spring
#      - postgres-main
#    volumes:
#      - ./keystore:/opt/alfresco-search-services/solrhome/alfresco/keystore
#      - ./config/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
#      - ./config/solrcore.properties:/usr/local/tomcat/shared/classes/solrcore.properties
#  solr6:
#    container_name: solr6
#    image: alfresco/alfresco-search-services:2.0.11
#    environment:
#      SOLR_ALFRESCO_HOST: "alfresco"
#      SOLR_ALFRESCO_PORT: "8080"
#      SOLR_SOLR_HOST: "solr6"
#      SOLR_SOLR_PORT: "8983"
#      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
#    ports:
#      - "8983:8983"
#    networks:
#      - spring
#      - postgres-main

networks:
    postgres-main:
        driver: bridge
    spring:
        driver: bridge

volumes:
    postgres:
    pgadmin:
#    alfresco-data:
#      driver: local
#    solr-data:
#      driver: local

##commands
#  mvn clean package -P build-docker-image
#  docker-compose up -d
