apiVersion: v1
kind: Service
metadata:
  name: resource-management
  namespace: itgura
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: resource-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092
  type: ClusterIP
