#springdoc:
#  enable-native-support: true
#  api-docs:
#    groups:
#      enabled: true
#    enabled: true
#  group-configs:
#    - group: dms-mediator
#      paths-to-match:
#        - /dms-mediator/**
#      display-name: dms-mediator
#    - group: resource-management
#      paths-to-match:
#        - /resource-management/**
#      display-name: resource-management
#  swagger-ui:
#    config-url: /v1/api-docs/swagger-config
#    url: /v1/api-docs
#    urls:
#      - url: /dms-mediator/v1/api-docs
#        name: dms-mediator
#      - url: /resource-management/v1/api-docs
#        name: resource-management