apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: itgura
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8098
  type: ClusterIP
  